#!/usr/bin/env php
<?php declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

use Narration\Console\Kernel;

/**
 * Gets the Application Commands.
 */
$commands = require __DIR__ . '/config/routes/console.php';

/**
 * Capture the input from globals.
 */
$input = new Symfony\Component\Console\Input\ArgvInput();

/**
 * Dispatch the request using the kernel.
 */
Kernel::attach($commands)->dispatch($input);
